title: CUCyber @ Columbia
subtitle: Cyber Security Practice & Capture The Flag Student Organization
url: "" # the base hostname & protocol for your site, e.g. http://example.com
description: >- # this means to ignore newlines until "nexttag:"
  Columbia University's student organization CUCyber webpage.
name: CUCyber
email: dennis.r@columbia.edu, george.litvinov@columbia.edu
mailinglist: https://lists.cs.columbia.edu/mailman/listinfo/cucyber
calendar: https://calendar.google.com/calendar/b/1/embed?src=columbia.edu_6k55l1c1q870ihnvgqke6t01nk@group.calendar.google.com&ctz=America/New_York
meetings: Thursdays 7:00 PM - 8:30 PM @CS Lounge 

# Supported social media
twitter: cucyberlions
facebook: cucyber
github: cuctf
slack: cucyber

plugins:
  - jekyll-feed
